x = frozenset({"apple", "banana", "cherry"})
print(x)
print(type(x))
print('----')
x = b"Hello"
print(x)
print(type(x))
print('----')
x = bytearray(5)
print(x)
print(type(x)) 
print('----')
x = memoryview(bytes(5))
print(x)
print(type(x)) 
print('----')